// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tlsn_mobileFFI)
import tlsn_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tlsn_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tlsn_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Reveal handler — specifies what to reveal in the proof.
 */
public struct Handler {
    public var handlerType: HandlerType
    public var part: HandlerPart
    public var action: HandlerAction
    public var params: HandlerParams?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(handlerType: HandlerType, part: HandlerPart, action: HandlerAction, params: HandlerParams?) {
        self.handlerType = handlerType
        self.part = part
        self.action = action
        self.params = params
    }
}



extension Handler: Equatable, Hashable {
    public static func ==(lhs: Handler, rhs: Handler) -> Bool {
        if lhs.handlerType != rhs.handlerType {
            return false
        }
        if lhs.part != rhs.part {
            return false
        }
        if lhs.action != rhs.action {
            return false
        }
        if lhs.params != rhs.params {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(handlerType)
        hasher.combine(part)
        hasher.combine(action)
        hasher.combine(params)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandler: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Handler {
        return
            try Handler(
                handlerType: FfiConverterTypeHandlerType.read(from: &buf), 
                part: FfiConverterTypeHandlerPart.read(from: &buf), 
                action: FfiConverterTypeHandlerAction.read(from: &buf), 
                params: FfiConverterOptionTypeHandlerParams.read(from: &buf)
        )
    }

    public static func write(_ value: Handler, into buf: inout [UInt8]) {
        FfiConverterTypeHandlerType.write(value.handlerType, into: &buf)
        FfiConverterTypeHandlerPart.write(value.part, into: &buf)
        FfiConverterTypeHandlerAction.write(value.action, into: &buf)
        FfiConverterOptionTypeHandlerParams.write(value.params, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandler_lift(_ buf: RustBuffer) throws -> Handler {
    return try FfiConverterTypeHandler.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandler_lower(_ value: Handler) -> RustBuffer {
    return FfiConverterTypeHandler.lower(value)
}


/**
 * Handler parameters for fine-grained control.
 */
public struct HandlerParams {
    public var key: String?
    public var hideKey: Bool?
    public var hideValue: Bool?
    public var contentType: String?
    public var path: String?
    public var regex: String?
    public var flags: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String?, hideKey: Bool?, hideValue: Bool?, contentType: String?, path: String?, regex: String?, flags: String?) {
        self.key = key
        self.hideKey = hideKey
        self.hideValue = hideValue
        self.contentType = contentType
        self.path = path
        self.regex = regex
        self.flags = flags
    }
}



extension HandlerParams: Equatable, Hashable {
    public static func ==(lhs: HandlerParams, rhs: HandlerParams) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.hideKey != rhs.hideKey {
            return false
        }
        if lhs.hideValue != rhs.hideValue {
            return false
        }
        if lhs.contentType != rhs.contentType {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.regex != rhs.regex {
            return false
        }
        if lhs.flags != rhs.flags {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(hideKey)
        hasher.combine(hideValue)
        hasher.combine(contentType)
        hasher.combine(path)
        hasher.combine(regex)
        hasher.combine(flags)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerParams {
        return
            try HandlerParams(
                key: FfiConverterOptionString.read(from: &buf), 
                hideKey: FfiConverterOptionBool.read(from: &buf), 
                hideValue: FfiConverterOptionBool.read(from: &buf), 
                contentType: FfiConverterOptionString.read(from: &buf), 
                path: FfiConverterOptionString.read(from: &buf), 
                regex: FfiConverterOptionString.read(from: &buf), 
                flags: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HandlerParams, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.key, into: &buf)
        FfiConverterOptionBool.write(value.hideKey, into: &buf)
        FfiConverterOptionBool.write(value.hideValue, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.regex, into: &buf)
        FfiConverterOptionString.write(value.flags, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerParams_lift(_ buf: RustBuffer) throws -> HandlerParams {
    return try FfiConverterTypeHandlerParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerParams_lower(_ value: HandlerParams) -> RustBuffer {
    return FfiConverterTypeHandlerParams.lower(value)
}


/**
 * HTTP header key-value pair.
 */
public struct HttpHeader {
    public var name: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }
}



extension HttpHeader: Equatable, Hashable {
    public static func ==(lhs: HttpHeader, rhs: HttpHeader) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpHeader {
        return
            try HttpHeader(
                name: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpHeader, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpHeader_lift(_ buf: RustBuffer) throws -> HttpHeader {
    return try FfiConverterTypeHttpHeader.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpHeader_lower(_ value: HttpHeader) -> RustBuffer {
    return FfiConverterTypeHttpHeader.lower(value)
}


/**
 * HTTP request to prove.
 */
public struct HttpRequest {
    public var url: String
    public var method: String
    public var headers: [HttpHeader]
    public var body: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, method: String, headers: [HttpHeader], body: String?) {
        self.url = url
        self.method = method
        self.headers = headers
        self.body = body
    }
}



extension HttpRequest: Equatable, Hashable {
    public static func ==(lhs: HttpRequest, rhs: HttpRequest) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.method != rhs.method {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(method)
        hasher.combine(headers)
        hasher.combine(body)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpRequest {
        return
            try HttpRequest(
                url: FfiConverterString.read(from: &buf), 
                method: FfiConverterString.read(from: &buf), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from: &buf), 
                body: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.method, into: &buf)
        FfiConverterSequenceTypeHttpHeader.write(value.headers, into: &buf)
        FfiConverterOptionString.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lift(_ buf: RustBuffer) throws -> HttpRequest {
    return try FfiConverterTypeHttpRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lower(_ value: HttpRequest) -> RustBuffer {
    return FfiConverterTypeHttpRequest.lower(value)
}


/**
 * HTTP response from the proven request.
 */
public struct HttpResponse {
    public var status: UInt16
    public var headers: [HttpHeader]
    public var body: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: UInt16, headers: [HttpHeader], body: String) {
        self.status = status
        self.headers = headers
        self.body = body
    }
}



extension HttpResponse: Equatable, Hashable {
    public static func ==(lhs: HttpResponse, rhs: HttpResponse) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(headers)
        hasher.combine(body)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpResponse {
        return
            try HttpResponse(
                status: FfiConverterUInt16.read(from: &buf), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from: &buf), 
                body: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpResponse, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.status, into: &buf)
        FfiConverterSequenceTypeHttpHeader.write(value.headers, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lift(_ buf: RustBuffer) throws -> HttpResponse {
    return try FfiConverterTypeHttpResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lower(_ value: HttpResponse) -> RustBuffer {
    return FfiConverterTypeHttpResponse.lower(value)
}


/**
 * Result of a proof operation.
 */
public struct ProofResult {
    public var response: HttpResponse
    public var transcript: Transcript
    public var handlersReceived: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(response: HttpResponse, transcript: Transcript, handlersReceived: UInt32) {
        self.response = response
        self.transcript = transcript
        self.handlersReceived = handlersReceived
    }
}



extension ProofResult: Equatable, Hashable {
    public static func ==(lhs: ProofResult, rhs: ProofResult) -> Bool {
        if lhs.response != rhs.response {
            return false
        }
        if lhs.transcript != rhs.transcript {
            return false
        }
        if lhs.handlersReceived != rhs.handlersReceived {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(response)
        hasher.combine(transcript)
        hasher.combine(handlersReceived)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofResult {
        return
            try ProofResult(
                response: FfiConverterTypeHttpResponse.read(from: &buf), 
                transcript: FfiConverterTypeTranscript.read(from: &buf), 
                handlersReceived: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ProofResult, into buf: inout [UInt8]) {
        FfiConverterTypeHttpResponse.write(value.response, into: &buf)
        FfiConverterTypeTranscript.write(value.transcript, into: &buf)
        FfiConverterUInt32.write(value.handlersReceived, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lift(_ buf: RustBuffer) throws -> ProofResult {
    return try FfiConverterTypeProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lower(_ value: ProofResult) -> RustBuffer {
    return FfiConverterTypeProofResult.lower(value)
}


/**
 * Prover options for the high-level prove function.
 */
public struct ProverOptions {
    public var verifierUrl: String
    public var maxSentData: UInt32
    public var maxRecvData: UInt32
    public var handlers: [Handler]
    public var mode: Mode?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(verifierUrl: String, maxSentData: UInt32, maxRecvData: UInt32, handlers: [Handler], mode: Mode?) {
        self.verifierUrl = verifierUrl
        self.maxSentData = maxSentData
        self.maxRecvData = maxRecvData
        self.handlers = handlers
        self.mode = mode
    }
}



extension ProverOptions: Equatable, Hashable {
    public static func ==(lhs: ProverOptions, rhs: ProverOptions) -> Bool {
        if lhs.verifierUrl != rhs.verifierUrl {
            return false
        }
        if lhs.maxSentData != rhs.maxSentData {
            return false
        }
        if lhs.maxRecvData != rhs.maxRecvData {
            return false
        }
        if lhs.handlers != rhs.handlers {
            return false
        }
        if lhs.mode != rhs.mode {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(verifierUrl)
        hasher.combine(maxSentData)
        hasher.combine(maxRecvData)
        hasher.combine(handlers)
        hasher.combine(mode)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProverOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProverOptions {
        return
            try ProverOptions(
                verifierUrl: FfiConverterString.read(from: &buf), 
                maxSentData: FfiConverterUInt32.read(from: &buf), 
                maxRecvData: FfiConverterUInt32.read(from: &buf), 
                handlers: FfiConverterSequenceTypeHandler.read(from: &buf), 
                mode: FfiConverterOptionTypeMode.read(from: &buf)
        )
    }

    public static func write(_ value: ProverOptions, into buf: inout [UInt8]) {
        FfiConverterString.write(value.verifierUrl, into: &buf)
        FfiConverterUInt32.write(value.maxSentData, into: &buf)
        FfiConverterUInt32.write(value.maxRecvData, into: &buf)
        FfiConverterSequenceTypeHandler.write(value.handlers, into: &buf)
        FfiConverterOptionTypeMode.write(value.mode, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProverOptions_lift(_ buf: RustBuffer) throws -> ProverOptions {
    return try FfiConverterTypeProverOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProverOptions_lower(_ value: ProverOptions) -> RustBuffer {
    return FfiConverterTypeProverOptions.lower(value)
}


/**
 * Output of [`prove_until_reveal`] — the prover paused after computing
 * reveal ranges. Pass [`session_id`] back to [`prove_finalize`] with an
 * approved bool to either complete the reveal or drop the session.
 */
public struct RevealPreparation {
    /**
     * Opaque handle the platform passes back to [`prove_finalize`].
     */
    public var sessionId: String
    /**
     * HTTP response received from the target server.
     */
    public var response: HttpResponse
    /**
     * One descriptor per annotated reveal range.
     */
    public var descriptors: [RevealRangeDescriptor]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque handle the platform passes back to [`prove_finalize`].
         */sessionId: String, 
        /**
         * HTTP response received from the target server.
         */response: HttpResponse, 
        /**
         * One descriptor per annotated reveal range.
         */descriptors: [RevealRangeDescriptor]) {
        self.sessionId = sessionId
        self.response = response
        self.descriptors = descriptors
    }
}



extension RevealPreparation: Equatable, Hashable {
    public static func ==(lhs: RevealPreparation, rhs: RevealPreparation) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.response != rhs.response {
            return false
        }
        if lhs.descriptors != rhs.descriptors {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(response)
        hasher.combine(descriptors)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRevealPreparation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RevealPreparation {
        return
            try RevealPreparation(
                sessionId: FfiConverterString.read(from: &buf), 
                response: FfiConverterTypeHttpResponse.read(from: &buf), 
                descriptors: FfiConverterSequenceTypeRevealRangeDescriptor.read(from: &buf)
        )
    }

    public static func write(_ value: RevealPreparation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterTypeHttpResponse.write(value.response, into: &buf)
        FfiConverterSequenceTypeRevealRangeDescriptor.write(value.descriptors, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRevealPreparation_lift(_ buf: RustBuffer) throws -> RevealPreparation {
    return try FfiConverterTypeRevealPreparation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRevealPreparation_lower(_ value: RevealPreparation) -> RustBuffer {
    return FfiConverterTypeRevealPreparation.lower(value)
}


/**
 * One row in the reveal-approval preview.
 *
 * Returned from [`prove_until_reveal`] for each annotated range that
 * `compute_reveal` produced. The user inspects these (in a native UI on the
 * JS side) and approves or rejects before [`prove_finalize`] runs.
 *
 * `preview` contains the actual transcript bytes for the range, decoded as
 * UTF-8 lossy. The platform layer is responsible for truncating/escaping
 * before display.
 */
public struct RevealRangeDescriptor {
    /**
     * "SENT" or "RECV"
     */
    public var direction: String
    /**
     * Human-readable label (e.g. "Recv body / JSON 'screen_name'").
     */
    public var label: String
    /**
     * "REVEAL" or "HASH"
     */
    public var action: String
    /**
     * Hash algorithm name when `action == "HASH"` (e.g. "Sha256"). None for REVEAL.
     */
    public var algorithm: String?
    /**
     * UTF-8 lossy slice of the actual transcript bytes covered by this range.
     */
    public var preview: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * "SENT" or "RECV"
         */direction: String, 
        /**
         * Human-readable label (e.g. "Recv body / JSON 'screen_name'").
         */label: String, 
        /**
         * "REVEAL" or "HASH"
         */action: String, 
        /**
         * Hash algorithm name when `action == "HASH"` (e.g. "Sha256"). None for REVEAL.
         */algorithm: String?, 
        /**
         * UTF-8 lossy slice of the actual transcript bytes covered by this range.
         */preview: String) {
        self.direction = direction
        self.label = label
        self.action = action
        self.algorithm = algorithm
        self.preview = preview
    }
}



extension RevealRangeDescriptor: Equatable, Hashable {
    public static func ==(lhs: RevealRangeDescriptor, rhs: RevealRangeDescriptor) -> Bool {
        if lhs.direction != rhs.direction {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        if lhs.action != rhs.action {
            return false
        }
        if lhs.algorithm != rhs.algorithm {
            return false
        }
        if lhs.preview != rhs.preview {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(direction)
        hasher.combine(label)
        hasher.combine(action)
        hasher.combine(algorithm)
        hasher.combine(preview)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRevealRangeDescriptor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RevealRangeDescriptor {
        return
            try RevealRangeDescriptor(
                direction: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                action: FfiConverterString.read(from: &buf), 
                algorithm: FfiConverterOptionString.read(from: &buf), 
                preview: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RevealRangeDescriptor, into buf: inout [UInt8]) {
        FfiConverterString.write(value.direction, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.action, into: &buf)
        FfiConverterOptionString.write(value.algorithm, into: &buf)
        FfiConverterString.write(value.preview, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRevealRangeDescriptor_lift(_ buf: RustBuffer) throws -> RevealRangeDescriptor {
    return try FfiConverterTypeRevealRangeDescriptor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRevealRangeDescriptor_lower(_ value: RevealRangeDescriptor) -> RustBuffer {
    return FfiConverterTypeRevealRangeDescriptor.lower(value)
}


/**
 * Transcript of the TLS session.
 */
public struct Transcript {
    public var sent: Data
    public var recv: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sent: Data, recv: Data) {
        self.sent = sent
        self.recv = recv
    }
}



extension Transcript: Equatable, Hashable {
    public static func ==(lhs: Transcript, rhs: Transcript) -> Bool {
        if lhs.sent != rhs.sent {
            return false
        }
        if lhs.recv != rhs.recv {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sent)
        hasher.combine(recv)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTranscript: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Transcript {
        return
            try Transcript(
                sent: FfiConverterData.read(from: &buf), 
                recv: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Transcript, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sent, into: &buf)
        FfiConverterData.write(value.recv, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTranscript_lift(_ buf: RustBuffer) throws -> Transcript {
    return try FfiConverterTypeTranscript.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTranscript_lower(_ value: Transcript) -> RustBuffer {
    return FfiConverterTypeTranscript.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Comparison operator for an ASSERT action (evaluated by the verifier).
 */

public enum AssertOp {
    
    case gt
    case gte
    case lt
    case lte
    case between
    case `in`
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssertOp: FfiConverterRustBuffer {
    typealias SwiftType = AssertOp

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssertOp {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .gt
        
        case 2: return .gte
        
        case 3: return .lt
        
        case 4: return .lte
        
        case 5: return .between
        
        case 6: return .`in`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AssertOp, into buf: inout [UInt8]) {
        switch value {
        
        
        case .gt:
            writeInt(&buf, Int32(1))
        
        
        case .gte:
            writeInt(&buf, Int32(2))
        
        
        case .lt:
            writeInt(&buf, Int32(3))
        
        
        case .lte:
            writeInt(&buf, Int32(4))
        
        
        case .between:
            writeInt(&buf, Int32(5))
        
        
        case .`in`:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssertOp_lift(_ buf: RustBuffer) throws -> AssertOp {
    return try FfiConverterTypeAssertOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssertOp_lower(_ value: AssertOp) -> RustBuffer {
    return FfiConverterTypeAssertOp.lower(value)
}



extension AssertOp: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How the verifier types an ASSERT comparison. Required for ordering ops and
 * `between`.
 */

public enum AssertValueType {
    
    case number
    case bigint
    case date
    case string
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssertValueType: FfiConverterRustBuffer {
    typealias SwiftType = AssertValueType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssertValueType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .number
        
        case 2: return .bigint
        
        case 3: return .date
        
        case 4: return .string
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AssertValueType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .number:
            writeInt(&buf, Int32(1))
        
        
        case .bigint:
            writeInt(&buf, Int32(2))
        
        
        case .date:
            writeInt(&buf, Int32(3))
        
        
        case .string:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssertValueType_lift(_ buf: RustBuffer) throws -> AssertValueType {
    return try FfiConverterTypeAssertValueType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssertValueType_lower(_ value: AssertValueType) -> RustBuffer {
    return FfiConverterTypeAssertValueType.lower(value)
}



extension AssertValueType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler action (what to do with the part).
 */

public enum HandlerAction {
    
    case reveal
    case hash(algorithm: HashAlgorithm
    )
    /**
     * Reveal the data (like `Reveal`) and have the verifier evaluate a
     * comparison against it. For `compute_reveal` this behaves as `Reveal`;
     * the assertion spec is carried to the verifier's `reveal_config`.
     */
    case assert(op: AssertOp, 
        /**
         * How to type the comparison (ordering ops + `between`).
         */valueType: AssertValueType?, 
        /**
         * Operands as strings (parsed per `value_type` by the verifier).
         */value: String?, min: String?, max: String?, inclusive: Bool?, 
        /**
         * Candidate values for `in`.
         */values: [String]?
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerAction: FfiConverterRustBuffer {
    typealias SwiftType = HandlerAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .reveal
        
        case 2: return .hash(algorithm: try FfiConverterTypeHashAlgorithm.read(from: &buf)
        )
        
        case 3: return .assert(op: try FfiConverterTypeAssertOp.read(from: &buf), valueType: try FfiConverterOptionTypeAssertValueType.read(from: &buf), value: try FfiConverterOptionString.read(from: &buf), min: try FfiConverterOptionString.read(from: &buf), max: try FfiConverterOptionString.read(from: &buf), inclusive: try FfiConverterOptionBool.read(from: &buf), values: try FfiConverterOptionSequenceString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .reveal:
            writeInt(&buf, Int32(1))
        
        
        case let .hash(algorithm):
            writeInt(&buf, Int32(2))
            FfiConverterTypeHashAlgorithm.write(algorithm, into: &buf)
            
        
        case let .assert(op,valueType,value,min,max,inclusive,values):
            writeInt(&buf, Int32(3))
            FfiConverterTypeAssertOp.write(op, into: &buf)
            FfiConverterOptionTypeAssertValueType.write(valueType, into: &buf)
            FfiConverterOptionString.write(value, into: &buf)
            FfiConverterOptionString.write(min, into: &buf)
            FfiConverterOptionString.write(max, into: &buf)
            FfiConverterOptionBool.write(inclusive, into: &buf)
            FfiConverterOptionSequenceString.write(values, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerAction_lift(_ buf: RustBuffer) throws -> HandlerAction {
    return try FfiConverterTypeHandlerAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerAction_lower(_ value: HandlerAction) -> RustBuffer {
    return FfiConverterTypeHandlerAction.lower(value)
}



extension HandlerAction: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler part (which part of the HTTP message to reveal).
 */

public enum HandlerPart {
    
    case startLine
    case `protocol`
    case method
    case requestTarget
    case statusCode
    case headers
    case body
    case all
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerPart: FfiConverterRustBuffer {
    typealias SwiftType = HandlerPart

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerPart {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .startLine
        
        case 2: return .`protocol`
        
        case 3: return .method
        
        case 4: return .requestTarget
        
        case 5: return .statusCode
        
        case 6: return .headers
        
        case 7: return .body
        
        case 8: return .all
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerPart, into buf: inout [UInt8]) {
        switch value {
        
        
        case .startLine:
            writeInt(&buf, Int32(1))
        
        
        case .`protocol`:
            writeInt(&buf, Int32(2))
        
        
        case .method:
            writeInt(&buf, Int32(3))
        
        
        case .requestTarget:
            writeInt(&buf, Int32(4))
        
        
        case .statusCode:
            writeInt(&buf, Int32(5))
        
        
        case .headers:
            writeInt(&buf, Int32(6))
        
        
        case .body:
            writeInt(&buf, Int32(7))
        
        
        case .all:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerPart_lift(_ buf: RustBuffer) throws -> HandlerPart {
    return try FfiConverterTypeHandlerPart.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerPart_lower(_ value: HandlerPart) -> RustBuffer {
    return FfiConverterTypeHandlerPart.lower(value)
}



extension HandlerPart: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler type (SENT or RECV).
 */

public enum HandlerType {
    
    case sent
    case recv
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerType: FfiConverterRustBuffer {
    typealias SwiftType = HandlerType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sent
        
        case 2: return .recv
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sent:
            writeInt(&buf, Int32(1))
        
        
        case .recv:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerType_lift(_ buf: RustBuffer) throws -> HandlerType {
    return try FfiConverterTypeHandlerType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerType_lower(_ value: HandlerType) -> RustBuffer {
    return FfiConverterTypeHandlerType.lower(value)
}



extension HandlerType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Hash algorithm for hash-commitment actions.
 */

public enum HashAlgorithm {
    
    case blake3
    case sha256
    case keccak256
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHashAlgorithm: FfiConverterRustBuffer {
    typealias SwiftType = HashAlgorithm

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HashAlgorithm {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .blake3
        
        case 2: return .sha256
        
        case 3: return .keccak256
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HashAlgorithm, into buf: inout [UInt8]) {
        switch value {
        
        
        case .blake3:
            writeInt(&buf, Int32(1))
        
        
        case .sha256:
            writeInt(&buf, Int32(2))
        
        
        case .keccak256:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHashAlgorithm_lift(_ buf: RustBuffer) throws -> HashAlgorithm {
    return try FfiConverterTypeHashAlgorithm.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHashAlgorithm_lower(_ value: HashAlgorithm) -> RustBuffer {
    return FfiConverterTypeHashAlgorithm.lower(value)
}



extension HashAlgorithm: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Protocol mode for the prover.
 */

public enum Mode {
    
    /**
     * MPC-TLS (default): co-runs the TLS handshake with the verifier.
     */
    case mpc
    /**
     * Proxy: notary observes the TLS session via its proxy endpoint.
     */
    case proxy
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMode: FfiConverterRustBuffer {
    typealias SwiftType = Mode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .mpc
        
        case 2: return .proxy
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Mode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .mpc:
            writeInt(&buf, Int32(1))
        
        
        case .proxy:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMode_lift(_ buf: RustBuffer) throws -> Mode {
    return try FfiConverterTypeMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMode_lower(_ value: Mode) -> RustBuffer {
    return FfiConverterTypeMode.lower(value)
}



extension Mode: Equatable, Hashable {}




/**
 * Error types for TLSN operations.
 */
public enum TlsnError {

    
    
    case InitializationFailed(String
    )
    case ConnectionFailed(String
    )
    case SetupFailed(String
    )
    case RequestFailed(String
    )
    case ProofFailed(String
    )
    case InvalidConfig(String
    )
    case Timeout
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTlsnError: FfiConverterRustBuffer {
    typealias SwiftType = TlsnError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TlsnError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConnectionFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .SetupFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .RequestFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .ProofFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InvalidConfig(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .Timeout

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TlsnError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InitializationFailed(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConnectionFailed(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SetupFailed(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RequestFailed(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ProofFailed(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidConfig(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .Timeout:
            writeInt(&buf, Int32(7))
        
        }
    }
}


extension TlsnError: Equatable, Hashable {}

extension TlsnError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Callback interface for receiving proof progress updates.
 *
 * Implement this on the Swift/Kotlin side to receive real-time progress
 * from the Rust prover. Each call includes:
 * - `step`: machine-readable step name (e.g. "MPC_SETUP")
 * - `progress`: 0.0–1.0 fraction
 * - `message`: human-readable description
 */
public protocol ProgressCallback : AnyObject {
    
    func onProgress(step: String, progress: Double, message: String) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceProgressCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceProgressCallback = UniffiVTableCallbackInterfaceProgressCallback(
        onProgress: { (
            uniffiHandle: UInt64,
            step: RustBuffer,
            progress: Double,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     step: try FfiConverterString.lift(step),
                     progress: try FfiConverterDouble.lift(progress),
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceProgressCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ProgressCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitProgressCallback() {
    uniffi_tlsn_mobile_fn_init_callback_vtable_progresscallback(&UniffiCallbackInterfaceProgressCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceProgressCallback {
    fileprivate static var handleMap = UniffiHandleMap<ProgressCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceProgressCallback : FfiConverter {
    typealias SwiftType = ProgressCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHandlerParams: FfiConverterRustBuffer {
    typealias SwiftType = HandlerParams?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHandlerParams.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHandlerParams.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAssertValueType: FfiConverterRustBuffer {
    typealias SwiftType = AssertValueType?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAssertValueType.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAssertValueType.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMode: FfiConverterRustBuffer {
    typealias SwiftType = Mode?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMode.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMode.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceProgressCallback: FfiConverterRustBuffer {
    typealias SwiftType = ProgressCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceProgressCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceProgressCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHandler: FfiConverterRustBuffer {
    typealias SwiftType = [Handler]

    public static func write(_ value: [Handler], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHandler.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Handler] {
        let len: Int32 = try readInt(&buf)
        var seq = [Handler]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHandler.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHttpHeader: FfiConverterRustBuffer {
    typealias SwiftType = [HttpHeader]

    public static func write(_ value: [HttpHeader], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHttpHeader.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HttpHeader] {
        let len: Int32 = try readInt(&buf)
        var seq = [HttpHeader]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHttpHeader.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRevealRangeDescriptor: FfiConverterRustBuffer {
    typealias SwiftType = [RevealRangeDescriptor]

    public static func write(_ value: [RevealRangeDescriptor], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRevealRangeDescriptor.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RevealRangeDescriptor] {
        let len: Int32 = try readInt(&buf)
        var seq = [RevealRangeDescriptor]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRevealRangeDescriptor.read(from: &buf))
        }
        return seq
    }
}
/**
 * Initialize the TLSN library. Call this once at app startup.
 */
public func initialize()throws  {try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_initialize($0
    )
}
}
/**
 * Legacy one-shot `prove`. Equivalent to [`prove_until_reveal`] followed by
 * [`prove_finalize`] with `approved=true`. Kept for backward compatibility
 * while callers migrate to the two-phase API.
 */
public func prove(request: HttpRequest, options: ProverOptions, progress: ProgressCallback?)throws  -> ProofResult {
    return try  FfiConverterTypeProofResult.lift(try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_prove(
        FfiConverterTypeHttpRequest.lower(request),
        FfiConverterTypeProverOptions.lower(options),
        FfiConverterOptionCallbackInterfaceProgressCallback.lower(progress),$0
    )
})
}
/**
 * Phase B of the two-phase prove flow.
 *
 * Looks up the session, then either:
 * - `approved == true`: runs `prover.reveal(...)`, sends `reveal_config` to
 * the verifier, awaits `session_completed`, returns the [`ProofResult`].
 * - `approved == false`: drops the session, closes the verifier websocket,
 * returns `TlsnError::ProofFailed("User rejected reveal")`.
 */
public func proveFinalize(sessionId: String, approved: Bool, progress: ProgressCallback?)throws  -> ProofResult {
    return try  FfiConverterTypeProofResult.lift(try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_prove_finalize(
        FfiConverterString.lower(sessionId),
        FfiConverterBool.lower(approved),
        FfiConverterOptionCallbackInterfaceProgressCallback.lower(progress),$0
    )
})
}
/**
 * Phase A of the two-phase prove flow.
 *
 * Runs:
 * 1. Register session with verifier
 * 2. Create prover and MPC setup
 * 3. Send HTTP request through TLS prover
 * 4. Compute reveal ranges from handlers
 *
 * Returns a [`RevealPreparation`] with byte-level previews of every range
 * the prover is about to reveal/hash. The platform shows the previews to
 * the user, then calls [`prove_finalize`] with the same `session_id` and an
 * `approved` bool. State is held in a process-wide map with a 5-minute TTL.
 */
public func proveUntilReveal(request: HttpRequest, options: ProverOptions, progress: ProgressCallback?)throws  -> RevealPreparation {
    return try  FfiConverterTypeRevealPreparation.lift(try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_prove_until_reveal(
        FfiConverterTypeHttpRequest.lower(request),
        FfiConverterTypeProverOptions.lower(options),
        FfiConverterOptionCallbackInterfaceProgressCallback.lower(progress),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tlsn_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_initialize() != 2246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_prove() != 63143) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_prove_finalize() != 11544) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_prove_until_reveal() != 57369) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tlsn_mobile_checksum_method_progresscallback_on_progress() != 49206) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitProgressCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all