// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.tlsn_mobile

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_tlsn_mobile_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_tlsn_mobile_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "tlsn_mobile"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceProgressCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`step`: RustBuffer.ByValue,`progress`: Double,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("onProgress", "uniffiFree")
internal open class UniffiVTableCallbackInterfaceProgressCallback(
    @JvmField internal var `onProgress`: UniffiCallbackInterfaceProgressCallbackMethod0? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `onProgress`: UniffiCallbackInterfaceProgressCallbackMethod0? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfaceProgressCallback(`onProgress`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceProgressCallback) {
        `onProgress` = other.`onProgress`
        `uniffiFree` = other.`uniffiFree`
    }

}




































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "tlsn_mobile")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                uniffiCallbackInterfaceProgressCallback.register(lib)
                }
        }
        
    }

    fun uniffi_tlsn_mobile_fn_init_callback_vtable_progresscallback(`vtable`: UniffiVTableCallbackInterfaceProgressCallback,
    ): Unit
    fun uniffi_tlsn_mobile_fn_func_initialize(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_tlsn_mobile_fn_func_prove(`request`: RustBuffer.ByValue,`options`: RustBuffer.ByValue,`progress`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_tlsn_mobile_fn_func_prove_finalize(`sessionId`: RustBuffer.ByValue,`approved`: Byte,`progress`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_tlsn_mobile_fn_func_prove_until_reveal(`request`: RustBuffer.ByValue,`options`: RustBuffer.ByValue,`progress`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_tlsn_mobile_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_tlsn_mobile_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_tlsn_mobile_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_tlsn_mobile_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_tlsn_mobile_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_tlsn_mobile_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_tlsn_mobile_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_tlsn_mobile_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_tlsn_mobile_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_tlsn_mobile_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_tlsn_mobile_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_tlsn_mobile_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_tlsn_mobile_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_tlsn_mobile_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_tlsn_mobile_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_tlsn_mobile_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_tlsn_mobile_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_tlsn_mobile_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_tlsn_mobile_checksum_func_initialize(
    ): Short
    fun uniffi_tlsn_mobile_checksum_func_prove(
    ): Short
    fun uniffi_tlsn_mobile_checksum_func_prove_finalize(
    ): Short
    fun uniffi_tlsn_mobile_checksum_func_prove_until_reveal(
    ): Short
    fun uniffi_tlsn_mobile_checksum_method_progresscallback_on_progress(
    ): Short
    fun ffi_tlsn_mobile_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_tlsn_mobile_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_tlsn_mobile_checksum_func_initialize() != 2246.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_tlsn_mobile_checksum_func_prove() != 63143.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_tlsn_mobile_checksum_func_prove_finalize() != 11544.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_tlsn_mobile_checksum_func_prove_until_reveal() != 57369.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_tlsn_mobile_checksum_method_progresscallback_on_progress() != 49206.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Reveal handler — specifies what to reveal in the proof.
 */
data class Handler (
    var `handlerType`: HandlerType, 
    var `part`: HandlerPart, 
    var `action`: HandlerAction, 
    var `params`: HandlerParams?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHandler: FfiConverterRustBuffer<Handler> {
    override fun read(buf: ByteBuffer): Handler {
        return Handler(
            FfiConverterTypeHandlerType.read(buf),
            FfiConverterTypeHandlerPart.read(buf),
            FfiConverterTypeHandlerAction.read(buf),
            FfiConverterOptionalTypeHandlerParams.read(buf),
        )
    }

    override fun allocationSize(value: Handler) = (
            FfiConverterTypeHandlerType.allocationSize(value.`handlerType`) +
            FfiConverterTypeHandlerPart.allocationSize(value.`part`) +
            FfiConverterTypeHandlerAction.allocationSize(value.`action`) +
            FfiConverterOptionalTypeHandlerParams.allocationSize(value.`params`)
    )

    override fun write(value: Handler, buf: ByteBuffer) {
            FfiConverterTypeHandlerType.write(value.`handlerType`, buf)
            FfiConverterTypeHandlerPart.write(value.`part`, buf)
            FfiConverterTypeHandlerAction.write(value.`action`, buf)
            FfiConverterOptionalTypeHandlerParams.write(value.`params`, buf)
    }
}



/**
 * Handler parameters for fine-grained control.
 */
data class HandlerParams (
    var `key`: kotlin.String?, 
    var `hideKey`: kotlin.Boolean?, 
    var `hideValue`: kotlin.Boolean?, 
    var `contentType`: kotlin.String?, 
    var `path`: kotlin.String?, 
    var `regex`: kotlin.String?, 
    var `flags`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHandlerParams: FfiConverterRustBuffer<HandlerParams> {
    override fun read(buf: ByteBuffer): HandlerParams {
        return HandlerParams(
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalBoolean.read(buf),
            FfiConverterOptionalBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: HandlerParams) = (
            FfiConverterOptionalString.allocationSize(value.`key`) +
            FfiConverterOptionalBoolean.allocationSize(value.`hideKey`) +
            FfiConverterOptionalBoolean.allocationSize(value.`hideValue`) +
            FfiConverterOptionalString.allocationSize(value.`contentType`) +
            FfiConverterOptionalString.allocationSize(value.`path`) +
            FfiConverterOptionalString.allocationSize(value.`regex`) +
            FfiConverterOptionalString.allocationSize(value.`flags`)
    )

    override fun write(value: HandlerParams, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`key`, buf)
            FfiConverterOptionalBoolean.write(value.`hideKey`, buf)
            FfiConverterOptionalBoolean.write(value.`hideValue`, buf)
            FfiConverterOptionalString.write(value.`contentType`, buf)
            FfiConverterOptionalString.write(value.`path`, buf)
            FfiConverterOptionalString.write(value.`regex`, buf)
            FfiConverterOptionalString.write(value.`flags`, buf)
    }
}



/**
 * HTTP header key-value pair.
 */
data class HttpHeader (
    var `name`: kotlin.String, 
    var `value`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHttpHeader: FfiConverterRustBuffer<HttpHeader> {
    override fun read(buf: ByteBuffer): HttpHeader {
        return HttpHeader(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: HttpHeader) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`value`)
    )

    override fun write(value: HttpHeader, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`value`, buf)
    }
}



/**
 * HTTP request to prove.
 */
data class HttpRequest (
    var `url`: kotlin.String, 
    var `method`: kotlin.String, 
    var `headers`: List<HttpHeader>, 
    var `body`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHttpRequest: FfiConverterRustBuffer<HttpRequest> {
    override fun read(buf: ByteBuffer): HttpRequest {
        return HttpRequest(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeHttpHeader.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: HttpRequest) = (
            FfiConverterString.allocationSize(value.`url`) +
            FfiConverterString.allocationSize(value.`method`) +
            FfiConverterSequenceTypeHttpHeader.allocationSize(value.`headers`) +
            FfiConverterOptionalString.allocationSize(value.`body`)
    )

    override fun write(value: HttpRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`url`, buf)
            FfiConverterString.write(value.`method`, buf)
            FfiConverterSequenceTypeHttpHeader.write(value.`headers`, buf)
            FfiConverterOptionalString.write(value.`body`, buf)
    }
}



/**
 * HTTP response from the proven request.
 */
data class HttpResponse (
    var `status`: kotlin.UShort, 
    var `headers`: List<HttpHeader>, 
    var `body`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHttpResponse: FfiConverterRustBuffer<HttpResponse> {
    override fun read(buf: ByteBuffer): HttpResponse {
        return HttpResponse(
            FfiConverterUShort.read(buf),
            FfiConverterSequenceTypeHttpHeader.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: HttpResponse) = (
            FfiConverterUShort.allocationSize(value.`status`) +
            FfiConverterSequenceTypeHttpHeader.allocationSize(value.`headers`) +
            FfiConverterString.allocationSize(value.`body`)
    )

    override fun write(value: HttpResponse, buf: ByteBuffer) {
            FfiConverterUShort.write(value.`status`, buf)
            FfiConverterSequenceTypeHttpHeader.write(value.`headers`, buf)
            FfiConverterString.write(value.`body`, buf)
    }
}



/**
 * Result of a proof operation.
 */
data class ProofResult (
    var `response`: HttpResponse, 
    var `transcript`: Transcript, 
    var `handlersReceived`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProofResult: FfiConverterRustBuffer<ProofResult> {
    override fun read(buf: ByteBuffer): ProofResult {
        return ProofResult(
            FfiConverterTypeHttpResponse.read(buf),
            FfiConverterTypeTranscript.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ProofResult) = (
            FfiConverterTypeHttpResponse.allocationSize(value.`response`) +
            FfiConverterTypeTranscript.allocationSize(value.`transcript`) +
            FfiConverterUInt.allocationSize(value.`handlersReceived`)
    )

    override fun write(value: ProofResult, buf: ByteBuffer) {
            FfiConverterTypeHttpResponse.write(value.`response`, buf)
            FfiConverterTypeTranscript.write(value.`transcript`, buf)
            FfiConverterUInt.write(value.`handlersReceived`, buf)
    }
}



/**
 * Prover options for the high-level prove function.
 */
data class ProverOptions (
    var `verifierUrl`: kotlin.String, 
    var `maxSentData`: kotlin.UInt, 
    var `maxRecvData`: kotlin.UInt, 
    var `handlers`: List<Handler>, 
    var `mode`: Mode?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProverOptions: FfiConverterRustBuffer<ProverOptions> {
    override fun read(buf: ByteBuffer): ProverOptions {
        return ProverOptions(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterSequenceTypeHandler.read(buf),
            FfiConverterOptionalTypeMode.read(buf),
        )
    }

    override fun allocationSize(value: ProverOptions) = (
            FfiConverterString.allocationSize(value.`verifierUrl`) +
            FfiConverterUInt.allocationSize(value.`maxSentData`) +
            FfiConverterUInt.allocationSize(value.`maxRecvData`) +
            FfiConverterSequenceTypeHandler.allocationSize(value.`handlers`) +
            FfiConverterOptionalTypeMode.allocationSize(value.`mode`)
    )

    override fun write(value: ProverOptions, buf: ByteBuffer) {
            FfiConverterString.write(value.`verifierUrl`, buf)
            FfiConverterUInt.write(value.`maxSentData`, buf)
            FfiConverterUInt.write(value.`maxRecvData`, buf)
            FfiConverterSequenceTypeHandler.write(value.`handlers`, buf)
            FfiConverterOptionalTypeMode.write(value.`mode`, buf)
    }
}



/**
 * Output of [`prove_until_reveal`] — the prover paused after computing
 * reveal ranges. Pass [`session_id`] back to [`prove_finalize`] with an
 * approved bool to either complete the reveal or drop the session.
 */
data class RevealPreparation (
    /**
     * Opaque handle the platform passes back to [`prove_finalize`].
     */
    var `sessionId`: kotlin.String, 
    /**
     * HTTP response received from the target server.
     */
    var `response`: HttpResponse, 
    /**
     * One descriptor per annotated reveal range.
     */
    var `descriptors`: List<RevealRangeDescriptor>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRevealPreparation: FfiConverterRustBuffer<RevealPreparation> {
    override fun read(buf: ByteBuffer): RevealPreparation {
        return RevealPreparation(
            FfiConverterString.read(buf),
            FfiConverterTypeHttpResponse.read(buf),
            FfiConverterSequenceTypeRevealRangeDescriptor.read(buf),
        )
    }

    override fun allocationSize(value: RevealPreparation) = (
            FfiConverterString.allocationSize(value.`sessionId`) +
            FfiConverterTypeHttpResponse.allocationSize(value.`response`) +
            FfiConverterSequenceTypeRevealRangeDescriptor.allocationSize(value.`descriptors`)
    )

    override fun write(value: RevealPreparation, buf: ByteBuffer) {
            FfiConverterString.write(value.`sessionId`, buf)
            FfiConverterTypeHttpResponse.write(value.`response`, buf)
            FfiConverterSequenceTypeRevealRangeDescriptor.write(value.`descriptors`, buf)
    }
}



/**
 * One row in the reveal-approval preview.
 *
 * Returned from [`prove_until_reveal`] for each annotated range that
 * `compute_reveal` produced. The user inspects these (in a native UI on the
 * JS side) and approves or rejects before [`prove_finalize`] runs.
 *
 * `preview` contains the actual transcript bytes for the range, decoded as
 * UTF-8 lossy. The platform layer is responsible for truncating/escaping
 * before display.
 */
data class RevealRangeDescriptor (
    /**
     * "SENT" or "RECV"
     */
    var `direction`: kotlin.String, 
    /**
     * Human-readable label (e.g. "Recv body / JSON 'screen_name'").
     */
    var `label`: kotlin.String, 
    /**
     * "REVEAL" or "HASH"
     */
    var `action`: kotlin.String, 
    /**
     * Hash algorithm name when `action == "HASH"` (e.g. "Sha256"). None for REVEAL.
     */
    var `algorithm`: kotlin.String?, 
    /**
     * UTF-8 lossy slice of the actual transcript bytes covered by this range.
     */
    var `preview`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRevealRangeDescriptor: FfiConverterRustBuffer<RevealRangeDescriptor> {
    override fun read(buf: ByteBuffer): RevealRangeDescriptor {
        return RevealRangeDescriptor(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: RevealRangeDescriptor) = (
            FfiConverterString.allocationSize(value.`direction`) +
            FfiConverterString.allocationSize(value.`label`) +
            FfiConverterString.allocationSize(value.`action`) +
            FfiConverterOptionalString.allocationSize(value.`algorithm`) +
            FfiConverterString.allocationSize(value.`preview`)
    )

    override fun write(value: RevealRangeDescriptor, buf: ByteBuffer) {
            FfiConverterString.write(value.`direction`, buf)
            FfiConverterString.write(value.`label`, buf)
            FfiConverterString.write(value.`action`, buf)
            FfiConverterOptionalString.write(value.`algorithm`, buf)
            FfiConverterString.write(value.`preview`, buf)
    }
}



/**
 * Transcript of the TLS session.
 */
data class Transcript (
    var `sent`: kotlin.ByteArray, 
    var `recv`: kotlin.ByteArray
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTranscript: FfiConverterRustBuffer<Transcript> {
    override fun read(buf: ByteBuffer): Transcript {
        return Transcript(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: Transcript) = (
            FfiConverterByteArray.allocationSize(value.`sent`) +
            FfiConverterByteArray.allocationSize(value.`recv`)
    )

    override fun write(value: Transcript, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`sent`, buf)
            FfiConverterByteArray.write(value.`recv`, buf)
    }
}



/**
 * Comparison operator for an ASSERT action (evaluated by the verifier).
 */

enum class AssertOp {
    
    GT,
    GTE,
    LT,
    LTE,
    BETWEEN,
    IN;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAssertOp: FfiConverterRustBuffer<AssertOp> {
    override fun read(buf: ByteBuffer) = try {
        AssertOp.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AssertOp) = 4UL

    override fun write(value: AssertOp, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * How the verifier types an ASSERT comparison. Required for ordering ops and
 * `between`.
 */

enum class AssertValueType {
    
    NUMBER,
    BIGINT,
    DATE,
    STRING;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAssertValueType: FfiConverterRustBuffer<AssertValueType> {
    override fun read(buf: ByteBuffer) = try {
        AssertValueType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AssertValueType) = 4UL

    override fun write(value: AssertValueType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Handler action (what to do with the part).
 */
sealed class HandlerAction {
    
    object Reveal : HandlerAction()
    
    
    data class Hash(
        val `algorithm`: HashAlgorithm) : HandlerAction() {
        companion object
    }
    
    /**
     * Reveal the data (like `Reveal`) and have the verifier evaluate a
     * comparison against it. For `compute_reveal` this behaves as `Reveal`;
     * the assertion spec is carried to the verifier's `reveal_config`.
     */
    data class Assert(
        val `op`: AssertOp, 
        /**
         * How to type the comparison (ordering ops + `between`).
         */
        val `valueType`: AssertValueType?, 
        /**
         * Operands as strings (parsed per `value_type` by the verifier).
         */
        val `value`: kotlin.String?, 
        val `min`: kotlin.String?, 
        val `max`: kotlin.String?, 
        val `inclusive`: kotlin.Boolean?, 
        /**
         * Candidate values for `in`.
         */
        val `values`: List<kotlin.String>?) : HandlerAction() {
        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHandlerAction : FfiConverterRustBuffer<HandlerAction>{
    override fun read(buf: ByteBuffer): HandlerAction {
        return when(buf.getInt()) {
            1 -> HandlerAction.Reveal
            2 -> HandlerAction.Hash(
                FfiConverterTypeHashAlgorithm.read(buf),
                )
            3 -> HandlerAction.Assert(
                FfiConverterTypeAssertOp.read(buf),
                FfiConverterOptionalTypeAssertValueType.read(buf),
                FfiConverterOptionalString.read(buf),
                FfiConverterOptionalString.read(buf),
                FfiConverterOptionalString.read(buf),
                FfiConverterOptionalBoolean.read(buf),
                FfiConverterOptionalSequenceString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: HandlerAction) = when(value) {
        is HandlerAction.Reveal -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is HandlerAction.Hash -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeHashAlgorithm.allocationSize(value.`algorithm`)
            )
        }
        is HandlerAction.Assert -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeAssertOp.allocationSize(value.`op`)
                + FfiConverterOptionalTypeAssertValueType.allocationSize(value.`valueType`)
                + FfiConverterOptionalString.allocationSize(value.`value`)
                + FfiConverterOptionalString.allocationSize(value.`min`)
                + FfiConverterOptionalString.allocationSize(value.`max`)
                + FfiConverterOptionalBoolean.allocationSize(value.`inclusive`)
                + FfiConverterOptionalSequenceString.allocationSize(value.`values`)
            )
        }
    }

    override fun write(value: HandlerAction, buf: ByteBuffer) {
        when(value) {
            is HandlerAction.Reveal -> {
                buf.putInt(1)
                Unit
            }
            is HandlerAction.Hash -> {
                buf.putInt(2)
                FfiConverterTypeHashAlgorithm.write(value.`algorithm`, buf)
                Unit
            }
            is HandlerAction.Assert -> {
                buf.putInt(3)
                FfiConverterTypeAssertOp.write(value.`op`, buf)
                FfiConverterOptionalTypeAssertValueType.write(value.`valueType`, buf)
                FfiConverterOptionalString.write(value.`value`, buf)
                FfiConverterOptionalString.write(value.`min`, buf)
                FfiConverterOptionalString.write(value.`max`, buf)
                FfiConverterOptionalBoolean.write(value.`inclusive`, buf)
                FfiConverterOptionalSequenceString.write(value.`values`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





/**
 * Handler part (which part of the HTTP message to reveal).
 */

enum class HandlerPart {
    
    START_LINE,
    PROTOCOL,
    METHOD,
    REQUEST_TARGET,
    STATUS_CODE,
    HEADERS,
    BODY,
    ALL;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeHandlerPart: FfiConverterRustBuffer<HandlerPart> {
    override fun read(buf: ByteBuffer) = try {
        HandlerPart.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HandlerPart) = 4UL

    override fun write(value: HandlerPart, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Handler type (SENT or RECV).
 */

enum class HandlerType {
    
    SENT,
    RECV;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeHandlerType: FfiConverterRustBuffer<HandlerType> {
    override fun read(buf: ByteBuffer) = try {
        HandlerType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HandlerType) = 4UL

    override fun write(value: HandlerType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Hash algorithm for hash-commitment actions.
 */

enum class HashAlgorithm {
    
    BLAKE3,
    SHA256,
    KECCAK256;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeHashAlgorithm: FfiConverterRustBuffer<HashAlgorithm> {
    override fun read(buf: ByteBuffer) = try {
        HashAlgorithm.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HashAlgorithm) = 4UL

    override fun write(value: HashAlgorithm, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Protocol mode for the prover.
 */

enum class Mode {
    
    /**
     * MPC-TLS (default): co-runs the TLS handshake with the verifier.
     */
    MPC,
    /**
     * Proxy: notary observes the TLS session via its proxy endpoint.
     */
    PROXY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMode: FfiConverterRustBuffer<Mode> {
    override fun read(buf: ByteBuffer) = try {
        Mode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Mode) = 4UL

    override fun write(value: Mode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







/**
 * Error types for TLSN operations.
 */
sealed class TlsnException: kotlin.Exception() {
    
    class InitializationFailed(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class ConnectionFailed(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class SetupFailed(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class RequestFailed(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class ProofFailed(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class InvalidConfig(
        
        val v1: kotlin.String
        ) : TlsnException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class Timeout(
        ) : TlsnException() {
        override val message
            get() = ""
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<TlsnException> {
        override fun lift(error_buf: RustBuffer.ByValue): TlsnException = FfiConverterTypeTlsnError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeTlsnError : FfiConverterRustBuffer<TlsnException> {
    override fun read(buf: ByteBuffer): TlsnException {
        

        return when(buf.getInt()) {
            1 -> TlsnException.InitializationFailed(
                FfiConverterString.read(buf),
                )
            2 -> TlsnException.ConnectionFailed(
                FfiConverterString.read(buf),
                )
            3 -> TlsnException.SetupFailed(
                FfiConverterString.read(buf),
                )
            4 -> TlsnException.RequestFailed(
                FfiConverterString.read(buf),
                )
            5 -> TlsnException.ProofFailed(
                FfiConverterString.read(buf),
                )
            6 -> TlsnException.InvalidConfig(
                FfiConverterString.read(buf),
                )
            7 -> TlsnException.Timeout()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: TlsnException): ULong {
        return when(value) {
            is TlsnException.InitializationFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.ConnectionFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.SetupFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.RequestFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.ProofFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.InvalidConfig -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TlsnException.Timeout -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: TlsnException, buf: ByteBuffer) {
        when(value) {
            is TlsnException.InitializationFailed -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.ConnectionFailed -> {
                buf.putInt(2)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.SetupFailed -> {
                buf.putInt(3)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.RequestFailed -> {
                buf.putInt(4)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.ProofFailed -> {
                buf.putInt(5)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.InvalidConfig -> {
                buf.putInt(6)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TlsnException.Timeout -> {
                buf.putInt(7)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





/**
 * Callback interface for receiving proof progress updates.
 *
 * Implement this on the Swift/Kotlin side to receive real-time progress
 * from the Rust prover. Each call includes:
 * - `step`: machine-readable step name (e.g. "MPC_SETUP")
 * - `progress`: 0.0–1.0 fraction
 * - `message`: human-readable description
 */
public interface ProgressCallback {
    
    fun `onProgress`(`step`: kotlin.String, `progress`: kotlin.Double, `message`: kotlin.String)
    
    companion object
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceProgressCallback {
    internal object `onProgress`: UniffiCallbackInterfaceProgressCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`step`: RustBuffer.ByValue,`progress`: Double,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeProgressCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onProgress`(
                    FfiConverterString.lift(`step`),
                    FfiConverterDouble.lift(`progress`),
                    FfiConverterString.lift(`message`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeProgressCallback.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceProgressCallback.UniffiByValue(
        `onProgress`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_tlsn_mobile_fn_init_callback_vtable_progresscallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeProgressCallback: FfiConverterCallbackInterface<ProgressCallback>()




/**
 * @suppress
 */
public object FfiConverterOptionalBoolean: FfiConverterRustBuffer<kotlin.Boolean?> {
    override fun read(buf: ByteBuffer): kotlin.Boolean? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterBoolean.read(buf)
    }

    override fun allocationSize(value: kotlin.Boolean?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterBoolean.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Boolean?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterBoolean.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeHandlerParams: FfiConverterRustBuffer<HandlerParams?> {
    override fun read(buf: ByteBuffer): HandlerParams? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeHandlerParams.read(buf)
    }

    override fun allocationSize(value: HandlerParams?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeHandlerParams.allocationSize(value)
        }
    }

    override fun write(value: HandlerParams?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeHandlerParams.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeAssertValueType: FfiConverterRustBuffer<AssertValueType?> {
    override fun read(buf: ByteBuffer): AssertValueType? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeAssertValueType.read(buf)
    }

    override fun allocationSize(value: AssertValueType?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeAssertValueType.allocationSize(value)
        }
    }

    override fun write(value: AssertValueType?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeAssertValueType.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeMode: FfiConverterRustBuffer<Mode?> {
    override fun read(buf: ByteBuffer): Mode? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeMode.read(buf)
    }

    override fun allocationSize(value: Mode?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeMode.allocationSize(value)
        }
    }

    override fun write(value: Mode?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeMode.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeProgressCallback: FfiConverterRustBuffer<ProgressCallback?> {
    override fun read(buf: ByteBuffer): ProgressCallback? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeProgressCallback.read(buf)
    }

    override fun allocationSize(value: ProgressCallback?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeProgressCallback.allocationSize(value)
        }
    }

    override fun write(value: ProgressCallback?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeProgressCallback.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalSequenceString: FfiConverterRustBuffer<List<kotlin.String>?> {
    override fun read(buf: ByteBuffer): List<kotlin.String>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterSequenceString.read(buf)
    }

    override fun allocationSize(value: List<kotlin.String>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterSequenceString.allocationSize(value)
        }
    }

    override fun write(value: List<kotlin.String>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterSequenceString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeHandler: FfiConverterRustBuffer<List<Handler>> {
    override fun read(buf: ByteBuffer): List<Handler> {
        val len = buf.getInt()
        return List<Handler>(len) {
            FfiConverterTypeHandler.read(buf)
        }
    }

    override fun allocationSize(value: List<Handler>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeHandler.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Handler>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeHandler.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeHttpHeader: FfiConverterRustBuffer<List<HttpHeader>> {
    override fun read(buf: ByteBuffer): List<HttpHeader> {
        val len = buf.getInt()
        return List<HttpHeader>(len) {
            FfiConverterTypeHttpHeader.read(buf)
        }
    }

    override fun allocationSize(value: List<HttpHeader>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeHttpHeader.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<HttpHeader>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeHttpHeader.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRevealRangeDescriptor: FfiConverterRustBuffer<List<RevealRangeDescriptor>> {
    override fun read(buf: ByteBuffer): List<RevealRangeDescriptor> {
        val len = buf.getInt()
        return List<RevealRangeDescriptor>(len) {
            FfiConverterTypeRevealRangeDescriptor.read(buf)
        }
    }

    override fun allocationSize(value: List<RevealRangeDescriptor>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRevealRangeDescriptor.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<RevealRangeDescriptor>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRevealRangeDescriptor.write(it, buf)
        }
    }
}
        /**
         * Initialize the TLSN library. Call this once at app startup.
         */
    @Throws(TlsnException::class) fun `initialize`()
        = 
    uniffiRustCallWithError(TlsnException) { _status ->
    UniffiLib.INSTANCE.uniffi_tlsn_mobile_fn_func_initialize(
        _status)
}
    
    

        /**
         * Legacy one-shot `prove`. Equivalent to [`prove_until_reveal`] followed by
         * [`prove_finalize`] with `approved=true`. Kept for backward compatibility
         * while callers migrate to the two-phase API.
         */
    @Throws(TlsnException::class) fun `prove`(`request`: HttpRequest, `options`: ProverOptions, `progress`: ProgressCallback?): ProofResult {
            return FfiConverterTypeProofResult.lift(
    uniffiRustCallWithError(TlsnException) { _status ->
    UniffiLib.INSTANCE.uniffi_tlsn_mobile_fn_func_prove(
        FfiConverterTypeHttpRequest.lower(`request`),FfiConverterTypeProverOptions.lower(`options`),FfiConverterOptionalTypeProgressCallback.lower(`progress`),_status)
}
    )
    }
    

        /**
         * Phase B of the two-phase prove flow.
         *
         * Looks up the session, then either:
         * - `approved == true`: runs `prover.reveal(...)`, sends `reveal_config` to
         * the verifier, awaits `session_completed`, returns the [`ProofResult`].
         * - `approved == false`: drops the session, closes the verifier websocket,
         * returns `TlsnError::ProofFailed("User rejected reveal")`.
         */
    @Throws(TlsnException::class) fun `proveFinalize`(`sessionId`: kotlin.String, `approved`: kotlin.Boolean, `progress`: ProgressCallback?): ProofResult {
            return FfiConverterTypeProofResult.lift(
    uniffiRustCallWithError(TlsnException) { _status ->
    UniffiLib.INSTANCE.uniffi_tlsn_mobile_fn_func_prove_finalize(
        FfiConverterString.lower(`sessionId`),FfiConverterBoolean.lower(`approved`),FfiConverterOptionalTypeProgressCallback.lower(`progress`),_status)
}
    )
    }
    

        /**
         * Phase A of the two-phase prove flow.
         *
         * Runs:
         * 1. Register session with verifier
         * 2. Create prover and MPC setup
         * 3. Send HTTP request through TLS prover
         * 4. Compute reveal ranges from handlers
         *
         * Returns a [`RevealPreparation`] with byte-level previews of every range
         * the prover is about to reveal/hash. The platform shows the previews to
         * the user, then calls [`prove_finalize`] with the same `session_id` and an
         * `approved` bool. State is held in a process-wide map with a 5-minute TTL.
         */
    @Throws(TlsnException::class) fun `proveUntilReveal`(`request`: HttpRequest, `options`: ProverOptions, `progress`: ProgressCallback?): RevealPreparation {
            return FfiConverterTypeRevealPreparation.lift(
    uniffiRustCallWithError(TlsnException) { _status ->
    UniffiLib.INSTANCE.uniffi_tlsn_mobile_fn_func_prove_until_reveal(
        FfiConverterTypeHttpRequest.lower(`request`),FfiConverterTypeProverOptions.lower(`options`),FfiConverterOptionalTypeProgressCallback.lower(`progress`),_status)
}
    )
    }
    


