#!/usr/bin/env node
/**
 * Build all plugins for demo and/or mobile targets.
 *
 * Usage:
 *   node build.js                  # Build both targets
 *   node build.js --target=demo    # Build demo only
 *   node build.js --target=mobile  # Build mobile only
 *
 * Environment variables:
 *   VITE_VERIFIER_HOST  - Verifier host (default: localhost:7047)
 *   VITE_SSL            - Use https/wss (default: false)
 *   MOBILE_VERIFIER_URL - Mobile verifier URL (default: http://localhost:7047)
 */
import * as esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const target =
  process.argv.find((a) => a.startsWith('--target='))?.split('=')[1] || 'all';

const plugins = ['twitter', 'swissbank', 'spotify', 'duolingo'];

// Demo configuration
const VERIFIER_HOST = process.env.VITE_VERIFIER_HOST || 'localhost:7047';
const SSL = process.env.VITE_SSL === 'true';
const DEMO_VERIFIER_URL = `${SSL ? 'https' : 'http'}://${VERIFIER_HOST}`;
const DEMO_PROXY_URL = `${SSL ? 'wss' : 'ws'}://${VERIFIER_HOST}/proxy?token=`;

// Mobile configuration
const MOBILE_VERIFIER_URL =
  process.env.MOBILE_VERIFIER_URL || 'http://localhost:7047';

fs.mkdirSync(path.resolve(__dirname, 'dist/demo'), { recursive: true });
fs.mkdirSync(path.resolve(__dirname, 'dist/mobile'), { recursive: true });

if (target === 'all' || target === 'demo') {
  console.log('Building plugins for DEMO...');
  console.log(`  VERIFIER_URL: ${DEMO_VERIFIER_URL}`);
  console.log(`  PROXY_URL:    ${DEMO_PROXY_URL}`);

  for (const plugin of plugins) {
    const entry = path.resolve(__dirname, `src/${plugin}.plugin.ts`);
    const outfile = path.resolve(__dirname, `dist/demo/${plugin}.js`);

    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      format: 'esm',
      outfile,
      define: {
        __VERIFIER_URL__: JSON.stringify(DEMO_VERIFIER_URL),
        __PROXY_URL__: JSON.stringify(DEMO_PROXY_URL),
      },
    });
    console.log(`  OK ${plugin}.js`);
  }
}

if (target === 'all' || target === 'mobile') {
  console.log('Building plugins for MOBILE...');
  console.log(`  VERIFIER_URL: ${MOBILE_VERIFIER_URL}`);
  console.log(`  PROXY_URL:    (empty)`);

  for (const plugin of plugins) {
    const entry = path.resolve(__dirname, `src/${plugin}.plugin.ts`);
    const tmpfile = path.resolve(__dirname, `dist/mobile/${plugin}.tmp.js`);
    const outfile = path.resolve(__dirname, `dist/mobile/${plugin}.ts`);

    // Bundle with esbuild (produces ESM JS)
    // IMPORTANT: Target es2016 to compile async/await into generator-based
    // promise chains. Hermes (React Native's JS engine) does NOT support
    // async/await in dynamically evaluated code — new Function() and eval()
    // bypass Metro's Babel transform, so the code must already be downleveled.
    // Without this, plugins fail with "async functions are unsupported".
    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      format: 'esm',
      target: 'es2016',
      outfile: tmpfile,
      define: {
        __VERIFIER_URL__: JSON.stringify(MOBILE_VERIFIER_URL),
        __PROXY_URL__: JSON.stringify(''),
      },
    });

    // Read the bundled code and transform for Function() evaluation.
    // esbuild ESM output ends with:
    //   var xxx_default = { main, onClick, ... };
    //   export { xxx_default as default };
    //
    // MobilePluginHost.evaluatePluginCode() wraps code in `new Function()`
    // and expects `export default { ... }` → transformed to `return { ... }`.
    // We strip the ESM export block and convert to a plain `return`.
    let code = fs.readFileSync(tmpfile, 'utf-8');

    // Replace `export {\n  xxx as default\n};\n` with `return xxx;`
    code = code.replace(
      /export\s*\{\s*(\w+)\s+as\s+default\s*\}\s*;?\s*$/,
      'return $1;',
    );

    const constName = plugin.toUpperCase() + '_PLUGIN_CODE';

    // Escape backticks and ${} in the code for template literal wrapping
    const escaped = code.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

    const moduleCode = `// Auto-generated by @tlsn/plugins build script — do not edit\nexport const ${constName} = \`${escaped}\`;\n`;
    fs.writeFileSync(outfile, moduleCode);
    fs.unlinkSync(tmpfile);

    console.log(`  OK ${plugin}.ts`);
  }
}

console.log('All plugins built successfully');
