// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tlsn_mobileFFI)
import tlsn_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tlsn_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tlsn_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Reveal handler — specifies what to reveal in the proof.
 */
public struct Handler {
    public var handlerType: HandlerType
    public var part: HandlerPart
    public var action: HandlerAction
    public var params: HandlerParams?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(handlerType: HandlerType, part: HandlerPart, action: HandlerAction, params: HandlerParams?) {
        self.handlerType = handlerType
        self.part = part
        self.action = action
        self.params = params
    }
}



extension Handler: Equatable, Hashable {
    public static func ==(lhs: Handler, rhs: Handler) -> Bool {
        if lhs.handlerType != rhs.handlerType {
            return false
        }
        if lhs.part != rhs.part {
            return false
        }
        if lhs.action != rhs.action {
            return false
        }
        if lhs.params != rhs.params {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(handlerType)
        hasher.combine(part)
        hasher.combine(action)
        hasher.combine(params)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandler: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Handler {
        return
            try Handler(
                handlerType: FfiConverterTypeHandlerType.read(from: &buf), 
                part: FfiConverterTypeHandlerPart.read(from: &buf), 
                action: FfiConverterTypeHandlerAction.read(from: &buf), 
                params: FfiConverterOptionTypeHandlerParams.read(from: &buf)
        )
    }

    public static func write(_ value: Handler, into buf: inout [UInt8]) {
        FfiConverterTypeHandlerType.write(value.handlerType, into: &buf)
        FfiConverterTypeHandlerPart.write(value.part, into: &buf)
        FfiConverterTypeHandlerAction.write(value.action, into: &buf)
        FfiConverterOptionTypeHandlerParams.write(value.params, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandler_lift(_ buf: RustBuffer) throws -> Handler {
    return try FfiConverterTypeHandler.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandler_lower(_ value: Handler) -> RustBuffer {
    return FfiConverterTypeHandler.lower(value)
}


/**
 * Handler parameters for fine-grained control.
 */
public struct HandlerParams {
    public var key: String?
    public var hideKey: Bool?
    public var hideValue: Bool?
    public var contentType: String?
    public var path: String?
    public var regex: String?
    public var flags: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String?, hideKey: Bool?, hideValue: Bool?, contentType: String?, path: String?, regex: String?, flags: String?) {
        self.key = key
        self.hideKey = hideKey
        self.hideValue = hideValue
        self.contentType = contentType
        self.path = path
        self.regex = regex
        self.flags = flags
    }
}



extension HandlerParams: Equatable, Hashable {
    public static func ==(lhs: HandlerParams, rhs: HandlerParams) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.hideKey != rhs.hideKey {
            return false
        }
        if lhs.hideValue != rhs.hideValue {
            return false
        }
        if lhs.contentType != rhs.contentType {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.regex != rhs.regex {
            return false
        }
        if lhs.flags != rhs.flags {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(hideKey)
        hasher.combine(hideValue)
        hasher.combine(contentType)
        hasher.combine(path)
        hasher.combine(regex)
        hasher.combine(flags)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerParams {
        return
            try HandlerParams(
                key: FfiConverterOptionString.read(from: &buf), 
                hideKey: FfiConverterOptionBool.read(from: &buf), 
                hideValue: FfiConverterOptionBool.read(from: &buf), 
                contentType: FfiConverterOptionString.read(from: &buf), 
                path: FfiConverterOptionString.read(from: &buf), 
                regex: FfiConverterOptionString.read(from: &buf), 
                flags: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HandlerParams, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.key, into: &buf)
        FfiConverterOptionBool.write(value.hideKey, into: &buf)
        FfiConverterOptionBool.write(value.hideValue, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.regex, into: &buf)
        FfiConverterOptionString.write(value.flags, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerParams_lift(_ buf: RustBuffer) throws -> HandlerParams {
    return try FfiConverterTypeHandlerParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerParams_lower(_ value: HandlerParams) -> RustBuffer {
    return FfiConverterTypeHandlerParams.lower(value)
}


/**
 * HTTP header key-value pair.
 */
public struct HttpHeader {
    public var name: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }
}



extension HttpHeader: Equatable, Hashable {
    public static func ==(lhs: HttpHeader, rhs: HttpHeader) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpHeader {
        return
            try HttpHeader(
                name: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpHeader, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpHeader_lift(_ buf: RustBuffer) throws -> HttpHeader {
    return try FfiConverterTypeHttpHeader.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpHeader_lower(_ value: HttpHeader) -> RustBuffer {
    return FfiConverterTypeHttpHeader.lower(value)
}


/**
 * HTTP request to prove.
 */
public struct HttpRequest {
    public var url: String
    public var method: String
    public var headers: [HttpHeader]
    public var body: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, method: String, headers: [HttpHeader], body: String?) {
        self.url = url
        self.method = method
        self.headers = headers
        self.body = body
    }
}



extension HttpRequest: Equatable, Hashable {
    public static func ==(lhs: HttpRequest, rhs: HttpRequest) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.method != rhs.method {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(method)
        hasher.combine(headers)
        hasher.combine(body)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpRequest {
        return
            try HttpRequest(
                url: FfiConverterString.read(from: &buf), 
                method: FfiConverterString.read(from: &buf), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from: &buf), 
                body: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.method, into: &buf)
        FfiConverterSequenceTypeHttpHeader.write(value.headers, into: &buf)
        FfiConverterOptionString.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lift(_ buf: RustBuffer) throws -> HttpRequest {
    return try FfiConverterTypeHttpRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lower(_ value: HttpRequest) -> RustBuffer {
    return FfiConverterTypeHttpRequest.lower(value)
}


/**
 * HTTP response from the proven request.
 */
public struct HttpResponse {
    public var status: UInt16
    public var headers: [HttpHeader]
    public var body: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: UInt16, headers: [HttpHeader], body: String) {
        self.status = status
        self.headers = headers
        self.body = body
    }
}



extension HttpResponse: Equatable, Hashable {
    public static func ==(lhs: HttpResponse, rhs: HttpResponse) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(headers)
        hasher.combine(body)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpResponse {
        return
            try HttpResponse(
                status: FfiConverterUInt16.read(from: &buf), 
                headers: FfiConverterSequenceTypeHttpHeader.read(from: &buf), 
                body: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpResponse, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.status, into: &buf)
        FfiConverterSequenceTypeHttpHeader.write(value.headers, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lift(_ buf: RustBuffer) throws -> HttpResponse {
    return try FfiConverterTypeHttpResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lower(_ value: HttpResponse) -> RustBuffer {
    return FfiConverterTypeHttpResponse.lower(value)
}


/**
 * Result of a proof operation.
 */
public struct ProofResult {
    public var response: HttpResponse
    public var transcript: Transcript
    public var handlersReceived: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(response: HttpResponse, transcript: Transcript, handlersReceived: UInt32) {
        self.response = response
        self.transcript = transcript
        self.handlersReceived = handlersReceived
    }
}



extension ProofResult: Equatable, Hashable {
    public static func ==(lhs: ProofResult, rhs: ProofResult) -> Bool {
        if lhs.response != rhs.response {
            return false
        }
        if lhs.transcript != rhs.transcript {
            return false
        }
        if lhs.handlersReceived != rhs.handlersReceived {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(response)
        hasher.combine(transcript)
        hasher.combine(handlersReceived)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofResult {
        return
            try ProofResult(
                response: FfiConverterTypeHttpResponse.read(from: &buf), 
                transcript: FfiConverterTypeTranscript.read(from: &buf), 
                handlersReceived: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ProofResult, into buf: inout [UInt8]) {
        FfiConverterTypeHttpResponse.write(value.response, into: &buf)
        FfiConverterTypeTranscript.write(value.transcript, into: &buf)
        FfiConverterUInt32.write(value.handlersReceived, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lift(_ buf: RustBuffer) throws -> ProofResult {
    return try FfiConverterTypeProofResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofResult_lower(_ value: ProofResult) -> RustBuffer {
    return FfiConverterTypeProofResult.lower(value)
}


/**
 * Prover options for the high-level prove function.
 */
public struct ProverOptions {
    public var verifierUrl: String
    public var maxSentData: UInt32
    public var maxRecvData: UInt32
    public var handlers: [Handler]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(verifierUrl: String, maxSentData: UInt32, maxRecvData: UInt32, handlers: [Handler]) {
        self.verifierUrl = verifierUrl
        self.maxSentData = maxSentData
        self.maxRecvData = maxRecvData
        self.handlers = handlers
    }
}



extension ProverOptions: Equatable, Hashable {
    public static func ==(lhs: ProverOptions, rhs: ProverOptions) -> Bool {
        if lhs.verifierUrl != rhs.verifierUrl {
            return false
        }
        if lhs.maxSentData != rhs.maxSentData {
            return false
        }
        if lhs.maxRecvData != rhs.maxRecvData {
            return false
        }
        if lhs.handlers != rhs.handlers {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(verifierUrl)
        hasher.combine(maxSentData)
        hasher.combine(maxRecvData)
        hasher.combine(handlers)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProverOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProverOptions {
        return
            try ProverOptions(
                verifierUrl: FfiConverterString.read(from: &buf), 
                maxSentData: FfiConverterUInt32.read(from: &buf), 
                maxRecvData: FfiConverterUInt32.read(from: &buf), 
                handlers: FfiConverterSequenceTypeHandler.read(from: &buf)
        )
    }

    public static func write(_ value: ProverOptions, into buf: inout [UInt8]) {
        FfiConverterString.write(value.verifierUrl, into: &buf)
        FfiConverterUInt32.write(value.maxSentData, into: &buf)
        FfiConverterUInt32.write(value.maxRecvData, into: &buf)
        FfiConverterSequenceTypeHandler.write(value.handlers, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProverOptions_lift(_ buf: RustBuffer) throws -> ProverOptions {
    return try FfiConverterTypeProverOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProverOptions_lower(_ value: ProverOptions) -> RustBuffer {
    return FfiConverterTypeProverOptions.lower(value)
}


/**
 * Transcript of the TLS session.
 */
public struct Transcript {
    public var sent: Data
    public var recv: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sent: Data, recv: Data) {
        self.sent = sent
        self.recv = recv
    }
}



extension Transcript: Equatable, Hashable {
    public static func ==(lhs: Transcript, rhs: Transcript) -> Bool {
        if lhs.sent != rhs.sent {
            return false
        }
        if lhs.recv != rhs.recv {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sent)
        hasher.combine(recv)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTranscript: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Transcript {
        return
            try Transcript(
                sent: FfiConverterData.read(from: &buf), 
                recv: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: Transcript, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sent, into: &buf)
        FfiConverterData.write(value.recv, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTranscript_lift(_ buf: RustBuffer) throws -> Transcript {
    return try FfiConverterTypeTranscript.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTranscript_lower(_ value: Transcript) -> RustBuffer {
    return FfiConverterTypeTranscript.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler action (what to do with the part).
 */

public enum HandlerAction {
    
    case reveal
    case pedersen
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerAction: FfiConverterRustBuffer {
    typealias SwiftType = HandlerAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .reveal
        
        case 2: return .pedersen
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .reveal:
            writeInt(&buf, Int32(1))
        
        
        case .pedersen:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerAction_lift(_ buf: RustBuffer) throws -> HandlerAction {
    return try FfiConverterTypeHandlerAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerAction_lower(_ value: HandlerAction) -> RustBuffer {
    return FfiConverterTypeHandlerAction.lower(value)
}



extension HandlerAction: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler part (which part of the HTTP message to reveal).
 */

public enum HandlerPart {
    
    case startLine
    case `protocol`
    case method
    case requestTarget
    case statusCode
    case headers
    case body
    case all
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerPart: FfiConverterRustBuffer {
    typealias SwiftType = HandlerPart

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerPart {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .startLine
        
        case 2: return .`protocol`
        
        case 3: return .method
        
        case 4: return .requestTarget
        
        case 5: return .statusCode
        
        case 6: return .headers
        
        case 7: return .body
        
        case 8: return .all
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerPart, into buf: inout [UInt8]) {
        switch value {
        
        
        case .startLine:
            writeInt(&buf, Int32(1))
        
        
        case .`protocol`:
            writeInt(&buf, Int32(2))
        
        
        case .method:
            writeInt(&buf, Int32(3))
        
        
        case .requestTarget:
            writeInt(&buf, Int32(4))
        
        
        case .statusCode:
            writeInt(&buf, Int32(5))
        
        
        case .headers:
            writeInt(&buf, Int32(6))
        
        
        case .body:
            writeInt(&buf, Int32(7))
        
        
        case .all:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerPart_lift(_ buf: RustBuffer) throws -> HandlerPart {
    return try FfiConverterTypeHandlerPart.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerPart_lower(_ value: HandlerPart) -> RustBuffer {
    return FfiConverterTypeHandlerPart.lower(value)
}



extension HandlerPart: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Handler type (SENT or RECV).
 */

public enum HandlerType {
    
    case sent
    case recv
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerType: FfiConverterRustBuffer {
    typealias SwiftType = HandlerType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sent
        
        case 2: return .recv
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sent:
            writeInt(&buf, Int32(1))
        
        
        case .recv:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerType_lift(_ buf: RustBuffer) throws -> HandlerType {
    return try FfiConverterTypeHandlerType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerType_lower(_ value: HandlerType) -> RustBuffer {
    return FfiConverterTypeHandlerType.lower(value)
}



extension HandlerType: Equatable, Hashable {}




/**
 * Error types for TLSN operations.
 */
public enum TlsnError {

    
    
    case InitializationFailed(String
    )
    case ConnectionFailed(String
    )
    case SetupFailed(String
    )
    case RequestFailed(String
    )
    case ProofFailed(String
    )
    case InvalidConfig(String
    )
    case Timeout
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTlsnError: FfiConverterRustBuffer {
    typealias SwiftType = TlsnError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TlsnError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConnectionFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .SetupFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .RequestFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .ProofFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InvalidConfig(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .Timeout

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TlsnError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InitializationFailed(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConnectionFailed(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SetupFailed(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RequestFailed(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ProofFailed(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidConfig(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .Timeout:
            writeInt(&buf, Int32(7))
        
        }
    }
}


extension TlsnError: Equatable, Hashable {}

extension TlsnError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHandlerParams: FfiConverterRustBuffer {
    typealias SwiftType = HandlerParams?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHandlerParams.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHandlerParams.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHandler: FfiConverterRustBuffer {
    typealias SwiftType = [Handler]

    public static func write(_ value: [Handler], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHandler.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Handler] {
        let len: Int32 = try readInt(&buf)
        var seq = [Handler]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHandler.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHttpHeader: FfiConverterRustBuffer {
    typealias SwiftType = [HttpHeader]

    public static func write(_ value: [HttpHeader], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHttpHeader.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HttpHeader] {
        let len: Int32 = try readInt(&buf)
        var seq = [HttpHeader]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHttpHeader.read(from: &buf))
        }
        return seq
    }
}
/**
 * Initialize the TLSN library. Call this once at app startup.
 */
public func initialize()throws  {try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_initialize($0
    )
}
}
/**
 * High-level prove function.
 *
 * Handles the entire proof flow:
 * 1. Register session with verifier
 * 2. Create prover and MPC setup
 * 3. Send HTTP request through TLS prover
 * 4. Compute reveal ranges from handlers
 * 5. Generate and finalize proof
 * 6. Send reveal config to verifier session
 */
public func prove(request: HttpRequest, options: ProverOptions)throws  -> ProofResult {
    return try  FfiConverterTypeProofResult.lift(try rustCallWithError(FfiConverterTypeTlsnError.lift) {
    uniffi_tlsn_mobile_fn_func_prove(
        FfiConverterTypeHttpRequest.lower(request),
        FfiConverterTypeProverOptions.lower(options),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tlsn_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_initialize() != 2246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tlsn_mobile_checksum_func_prove() != 7977) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all