name: Publish to Chrome Web Store

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish to Google Play Store'
        required: true
        default: '0.1.0.703'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: tlsn-extension-${{ github.event.inputs.tag }}.zip

    # Get tokens as documented on 
    # * https://developer.chrome.com/docs/webstore/using-api#beforeyoubegin
    # * https://github.com/fregante/chrome-webstore-upload-keys?tab=readme-ov-file
    # 
    - name: 💨 Publish
      uses: browser-actions/release-chrome-extension@latest # https://github.com/browser-actions/release-chrome-extension/tree/latest/
      with:
        extension-id: "gcfkkledipjbgdbimfpijgbkhajiaaph"
        extension-path: tlsn-extension-${{ github.event.inputs.tag }}.zip
        oauth-client-id: ${{ secrets.OAUTH_CLIENT_ID }}
        oauth-client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
        oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}